info:
  description: "Service for Product Composite"

spring:
  application:
    name: product-composite-service

security:
  basic:
    enabled: false

server:
  port: 9092

#url:
  #productServiceURL: https://product-test-service/ProductService/productServiceStatus